/*
 * Copyright (c) 2016 Red Hat, Inc. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
package org.opendaylight.mdsal.binding.testutils;

import java.util.Collections;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.augment.rev140709.TreeComplexUsesAugment;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.augment.rev140709.TreeComplexUsesAugmentBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.augment.rev140709.complex.from.grouping.ContainerWithUses;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.augment.rev140709.complex.from.grouping.ContainerWithUsesBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.binding.rev140701.Top;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.binding.rev140701.TopBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.binding.rev140701.two.level.list.TopLevelList;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.binding.rev140701.two.level.list.TopLevelListBuilder;
import org.opendaylight.yang.gen.v1.urn.opendaylight.params.xml.ns.yang.mdsal.test.binding.rev140701.two.level.list.TopLevelListKey;

/**
 * The object initialization code in this class was generated by AssertDataObjects.
 *
 * @see AssertDataObjects
 * @see AssertDataObjectsTest
 */
public final class ExpectedObjects {

    private ExpectedObjects() {

    }

    public static TopLevelList topLevelList() {
        TopLevelListBuilder it = new TopLevelListBuilder();
        TopLevelListKey topLevelListKey = new TopLevelListKey("foo");
        it.withKey(topLevelListKey);
        it.setName("foo");
        TreeComplexUsesAugmentBuilder treeComplexUsesAugmentBuilder = new TreeComplexUsesAugmentBuilder();
        ContainerWithUsesBuilder containerWithUsesBuilder = new ContainerWithUsesBuilder();
        containerWithUsesBuilder.setLeafFromGrouping("foo");
        ContainerWithUses containerWithUses = containerWithUsesBuilder.build();
        treeComplexUsesAugmentBuilder.setContainerWithUses(containerWithUses);
        TreeComplexUsesAugment treeComplexUsesAugment = treeComplexUsesAugmentBuilder.build();
        it.addAugmentation(TreeComplexUsesAugment.class, treeComplexUsesAugment);
        return it.build();
    }

    public static Top top() {
        return new TopBuilder()
                .setTopLevelList(Collections.singletonList(new TopLevelListBuilder()
                    .setName("foo")
                    .addAugmentation(TreeComplexUsesAugment.class, new TreeComplexUsesAugmentBuilder()
                        .setContainerWithUses(new ContainerWithUsesBuilder().setLeafFromGrouping("foo").build())
                        .build())
                    .build()))
                .build();
    }
}
