<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright (c) 2026 PANTHEON.tech, s.r.o. and others.  All rights reserved.

 This program and the accompanying materials are made available under the
 terms of the Eclipse Public License v1.0 which accompanies this distribution,
 and is available at http://www.eclipse.org/legal/epl-v10.html
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.opendaylight.mdsal</groupId>
        <artifactId>template-feature-parent</artifactId>
        <version>17.0.0-SNAPSHOT</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>odl-mdsal-1node-dom</artifactId>
    <packaging>feature</packaging>

    <name>OpenDaylight :: MD-SAL :: Usecase :: 1-node DOM</name>
    <description>MD-SAL DOM layer for standalone instances</description>

    <dependencies>
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>odl-mdsal-dom</artifactId>
            <type>xml</type>
            <classifier>features</classifier>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>odl-mdsal-eos-single</artifactId>
            <type>xml</type>
            <classifier>features</classifier>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>odl-mdsal-singleton-dom</artifactId>
            <type>xml</type>
            <classifier>features</classifier>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.yangtools</groupId>
            <artifactId>odl-yangtools-data</artifactId>
            <type>xml</type>
            <classifier>features</classifier>
        </dependency>

        <!--

            FIXME: This does not quite work, as the configuration wiring is missing:

            We should be injecting a SCR-based implementation of OPER and CONFIG, each of which
            is disabled by default, but can be configured via ConfigAdmin.

            Activation be provided separately, in odl-mdsal-oper-imds with a default .json-based
            configuration.

            dom-store-inmemory should be packaged in od-mdsal-dom as the low-level integration
            with yang.data.tree.
        -->
        <dependency>
            <groupId>org.opendaylight.mdsal</groupId>
            <artifactId>dom-store-inmemory</artifactId>
        </dependency>
    </dependencies>
</project>
